#!/bin/sh
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

# Change ownership of media mount
chown -R daemon:daemon /home/daemon/MAS/media

# First run migrations
/home/daemon/miniconda/envs/mas/bin/python /home/daemon/MAS/manage.py makemigrations result_viewer
/home/daemon/miniconda/envs/mas/bin/python /home/daemon/MAS/manage.py migrate result_viewer

# Then run remaining migrations
/home/daemon/miniconda/envs/mas/bin/python /home/daemon/MAS/manage.py makemigrations
/home/daemon/miniconda/envs/mas/bin/python /home/daemon/MAS/manage.py migrate

# Then collect static files
/home/daemon/miniconda/envs/mas/bin/python /home/daemon/MAS/manage.py collectstatic --noinput

# Now load data and create users
/home/daemon/miniconda/envs/mas/bin/python /home/daemon/MAS/manage.py loaddata /home/daemon/MAS/genome/fixtures/groups.json
/home/daemon/miniconda/envs/mas/bin/python /home/daemon/MAS/manage.py createdefaultusers "${ADMIN_USER_PASSWORD}" "${LUIGI_USER_PASSWORD}"

# Finally run the PDB mappings update
# /home/daemon/miniconda/envs/mas/bin/python /home/daemon/MAS/manage.py updatepdbnamemappings /home/daemon/MAS/pdb_seqres.txt --override_existing

# Start luigi daemon from daemon account
sudo -u daemon nohup /home/daemon/miniconda/envs/mas/bin/luigid --logdir /home/daemon/MAS/luigi_logs --background &

# Start server
exec httpd -DFOREGROUND "$@"

